name: Request a feature
description: An idea for the app or its wallpapers.
labels: ['enhancement']
body:
  - type: textarea
    id: need
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Your proposal
      description: Describe the behavior and include an example if possible.
    validations:
      required: true
