name: Proposer une fonctionnalité
description: Une idée pour l'application ou les screeners.
labels: ['enhancement']
body:
  - type: textarea
    id: need
    attributes:
      label: Quel besoin souhaitez-vous résoudre ?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Votre proposition
      description: Décrivez le comportement et, si possible, un exemple.
    validations:
      required: true
